(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c2=function(a){a.R("cardstatechange",g.XW(a)&&g.YW(a)?1:0)},uBa=function(a){var b=g.ug(a);
a=g.Bg(a);return new g.eg(b.x,b.y,a.width,a.height)},vBa=function(a){return Math.pow(a,3)},wBa=function(a){return 3*a*a-2*a*a*a},f2=function(a){a=g.Ta(a);
delete d2[a];g.Vb(d2)&&e2&&e2.stop()},yBa=function(){e2||(e2=new g.G(function(){xBa()},20));
var a=e2;a.isActive()||a.start()},xBa=function(){var a=g.A();
g.Ib(d2,function(b){zBa(b,a)});
g.Vb(d2)||yBa()},g2=function(a,b,c,d){g.An.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.o=a;this.H=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.F=0;this.B=null},zBa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;ABa(a,a.progress);1==a.progress?(a.va=0,f2(a),a.Ze(),a.Qo()):a.vb()&&a.Av()},ABa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.o.length);for(var c=0;c<a.o.length;c++)a.coords[c]=(a.H[c]-a.o[c])*b+a.o[c]},BBa=function(a,b){g.Hl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.va},h2=function(a,b,c,d,e){g2.call(this,b,c,d,e);
this.element=a},i2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
h2.call(this,a,b,c,d,e)},j2=function(a){g.B.call(this);
this.u=a||window;this.o=[]},k2=function(a){return a.baseUrl||null},l2=function(a,b){return g.Ie(g.Oc(a,b,void 0),function(c){return!!c})},CBa=function(a,b,c){function d(xb){var Wa=xb.hovercardButton;
if(!Wa)return null;Wa=Wa.subscribeButtonRenderer;if(!Wa)return null;var fb=f(Wa.unsubscribedButtonText),ge=f(Wa.subscribedButtonText);if(Wa.subscribed){var yi=f(Wa.subscriberCountWithUnsubscribeText);var zi=f(Wa.subscriberCountText)}else yi=f(Wa.subscriberCountText),zi=f(Wa.subscriberCountWithSubscribeText);var Ag=null;return xb.signinEndpoint&&(Ag=g.Qb(xb,"signinEndpoint","webNavigationEndpointData","url"),!Ag)?null:fb&&(ge||Ag)?{subscribed:Wa.subscribed,subscribeText:fb,subscribeCount:yi,unsubscribeText:ge,
unsubscribeCount:zi,enabled:Wa.enabled,signinUrl:Ag,classic:xb.useClassicSubscribeButton}:null}
function e(xb){if(xb){var Wa=[],fb=xb.videoId;fb&&Wa.push("v="+fb);(fb=xb.playlistId)&&Wa.push("list="+fb);(xb=xb.startTimeSeconds)&&Wa.push("t="+xb);return"/watch?"+Wa.join("&")}}
function f(xb){if(!xb)return null;var Wa=xb.simpleText;return Wa?Wa:xb.runs?g.Oc(xb.runs,function(fb){return fb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,r=null,t=null,w=null,x=!1,z=null,D=null,E=null,H=null,M=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,q=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=g.Qb(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;q="new";(x=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"===
h?((E=g.Qb(l,"urlEndpoint","url"))&&(m=E),n=!0,q="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=g.Qb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Qb(b,"title","accessibility","accessibilityData","label");var P=b.endpoint?b.endpoint.clickTrackingParams:null,Qa="";if(b.metadata){var kb=f(b.metadata);kb&&(Qa=kb)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Qa,callToAction:f(b.callToAction),
eA:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:z,subscribersText:D,isSubscribe:x,targetUrl:m||null,DI:n,bd:P?{itct:P}:null,OP:q,qn:a?a:null,HI:b.isPlaceholder,impressionUrls:l2(b.impressionUrls||[],k2),wI:l2(b.hovercardShowUrls||[],k2),clickUrls:l2(l.loggingUrls||[],k2),visualElement:g.Gs(b.trackingParams),
productPrice:H,additionalFeesText:M}},m2=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:l2(a.impressionUrls||[],k2),elements:l2(a.elements||[],function(d,e){return CBa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Gs(a.trackingParams));return c},n2=function(a){g.AS.call(this,a);
this.A=this.endscreen=null;this.o={};this.C={};this.B=this.u=null;this.H=[];this.M=!0;this.F=0;a=a.N();this.J=g.bC(a)||g.dC(a);this.events=new g.ms(this);g.C(this,this.events);this.events.K(this.player,g.ED("creatorendscreen"),this.mJ);this.events.K(this.player,g.FD("creatorendscreen"),this.nJ);this.events.K(this.player,"resize",this.La);this.events.K(window,"focus",this.KO);this.load();var b=g.De("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.$f(this,function(){g.He(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},DBa=function(a){return a.player.getVideoData().Dc?"current":a.J?"new":"current"},o2=function(a){return"creator-endscreen-editor"===a.player.N().playerStyle},EBa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.A&&a.A.abort();c={method:"POST",Ze:function(e){var f=a.A=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=m2(f,DBa(a))));p2(a,f)},
kg:{v:c},withCredentials:!0};a.J&&(c.kg.ptype="embedded");var d=b.Kq;d&&(c.Lb={ad_tracking:d});if(b=g.QF(b))if(b=g.Jc(b),b=g.Fc(b))a.A=g.mq(b,c)},p2=function(a,b,c){c=void 0===c?!0:c;
g.cX(a.player,"creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.B.dispose(),a.B=null);for(var d=g.p(Object.values(a.o)),e=d.next();!e.done;e=d.next())e.value.dispose();a.o={};a.C={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.F=0;if((a.endscreen=b)&&b.elements){c&&FBa(a);c=[];d=new g.BD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.N().o||(a.u=new g.V({D:"div",I:"ytp-ce-shadow"}),g.jP(a.player,a.u.element,4),a.B=new g.FN(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=GBa(a,e);a.o[e.id]=f;a.C[e.id]=e;g.jP(a.player,f.element,4);var h=new g.BD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);HBa(a,f,e)}g.uM(a.player,
c);a.La()}},FBa=function(a){var b=g.Ks(),c=g.Ms();
c&&b&&a.endscreen.visualElement&&g.gt(c,b,a.endscreen.visualElement)},GBa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",da:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":b.qn||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",O:q2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",O:{href:r2(a,b.targetUrl),tabindex:"-1"},L:[{D:"div",da:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Gn(b.title||"")},U:b.title},{D:"div",I:"ytp-ce-video-duration",U:b.videoDuration||
void 0}]}]};c=new g.V(c);break;case "PLAYLIST":c={D:"div",da:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":b.qn||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",O:q2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",O:{href:r2(a,b.targetUrl),tabindex:"-1"},L:[{D:"div",da:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Gn(b.title||"")},U:b.title},{D:"div",I:"ytp-ce-playlist-count",
L:[{D:"div",I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",U:b.playlistLength||void 0}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",da:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":b.qn||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",L:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
L:[{D:"div",I:"ytp-ce-expanding-overlay-body",L:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{D:"a",da:["ytp-ce-channel-title","ytp-ce-link"],O:{href:r2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Gn(b.title||"")},U:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",L:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{D:"div",da:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],U:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:q2(b)}]};c=new g.V(c);var d=g.pe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.N().o){var e=null;var f=b.bd.itct}else e="endscreen",f=null;e=new g.gY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",da:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":b.qn||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",L:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",L:[{D:"div",I:"ytp-ce-expanding-overlay-body",
L:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{D:"div",I:"ytp-ce-website-title",O:{dir:g.Gn(b.title||"")},U:b.title},{D:"div",I:"ytp-ce-website-metadata",U:b.metadata},{D:"a",da:["ytp-ce-website-goto","ytp-ce-link"],O:{href:r2(a,b.targetUrl),target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:q2(b)},{D:"div",I:"ytp-ce-expanding-icon",O:IBa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
L:[{D:"div",I:"ytp-ce-merchandise-price",U:b.productPrice}]},b.additionalFeesText&&c.L.push({D:"div",I:"ytp-ce-merchandise-additional-fees",U:b.additionalFeesText})),c={D:"div",da:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":b.qn||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",L:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
L:[{D:"div",I:"ytp-ce-expanding-overlay-body",L:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{D:"div",I:"ytp-ce-merchandise-title",O:{dir:g.Gn(b.title||"")},U:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",U:b.metadata},{D:"a",da:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:r2(a,b.targetUrl),target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:q2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
U:b.callToAction||void 0}]}]},c=new g.V(c)}b.HI&&g.I(c.element,"ytp-ce-placeholder");return c},q2=function(a){if(a.eA)var b=a.eA.thumbnails;
return IBa(b?b[b.length-1].url:null)},IBa=function(a){return a?{style:"background-image: url("+a+")"}:{}},HBa=function(a,b,c){function d(m){m&&(b.ia("blur",function(){"none"!=m.style.display&&a.M&&m.focus()}),b.K(m,"focus",f),b.K(m,"blur",h))}
function e(m){a.F+=m;0<a.F?(g.I(b.element,"ytp-ce-force-expand"),s2(a,c.id,!0)):(g.yn(b.element,"ytp-ce-force-expand"),g.yn(b.element,"ytp-ce-element-hover"),s2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.ia("mouseenter",function(){t2(a,b,c)});
b.ia("mouseleave",function(){u2(a,b,c)});
a.player.N().o||b.ia("click",function(){g.I(b.element,"ytp-ce-element-hover")});
b.ia("click",function(m){JBa(a,c,m)});
b.ia("keypress",function(m){JBa(a,c,m)});
b.ia("focus",function(){t2(a,b,c)});
b.ia("blur",function(){u2(a,b,c)});
b.ia("touchstart",function(){t2(a,b,c)});
var l=g.re("ytp-ce-expanding-overlay-hider",b.element);l&&b.K(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.yn(b.element,"ytp-ce-element-hover");g.yn(b.element,"ytp-ce-force-expand")});
b.ia("keydown",function(m){a.M=9===m.keyCode&&!m.shiftKey});
d(g.re("ytp-sb-subscribe",b.element));d(g.re("ytp-sb-unsubscribe",b.element));b.ia("focus",f);b.ia("blur",h)},JBa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.wn(d,"ytp-ce-element");){g.wn(d,"subscribe-label")&&v2(a,b);
if(g.wn(d,"ytp-ce-channel-subscribe"))return;d=g.Je(d)}if(!d||g.wn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.o[b.id])u2(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.OP)v2(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Jc(r2(a,b.targetUrl)),c=g.Fc(c),g.sK(c,void 0,b.bd);else{var e=a.player.getVideoData().Dc,f=function(){var h=r2(a,b.targetUrl),l=b.bd,m=g.Vp(h);e&&m&&(m.v||m.list)?g.M0(a.player.app,m.v,l,m.list,!1,void 0):g.rK(h,
l)};
v2(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},r2=function(a,b){var c=a.player.N();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.GC(c)+b}else return"";return b},t2=function(a,b,c){g.wn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.I(b.element,"ytp-ce-element-hover"):a.player.N().o?(new g.G(function(){g.I(b.element,"ytp-ce-element-hover")},200)).start():g.I(b.element,"ytp-ce-element-hover"),w2(a,c.wI),s2(a,c.id,!0))},u2=function(a,b,c){g.yn(b.element,"ytp-ce-element-hover");
g.yn(b.element,"ytp-ce-force-expand");s2(a,c.id,!1)},s2=function(a,b,c){a.u&&(c?a.B.show():a.B.hide());
for(var d=g.p(Object.keys(a.o)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.J(a.o[e].element,"ytp-ce-element-shadow-show",c)},w2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||o2(a))c&&c();else{b=KBa(a,b);var e=0,f=!1,h=new g.G(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.rt(b[a],d)}},v2=function(a,b,c){w2(a,b.clickUrls,c);
(a=g.Ms())&&b.DI&&g.jt(a,b.visualElement)},KBa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(LBa(b[e],c));return d},LBa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},MBa=function(a){return Array.isArray(a)&&a.length?a[0]:a},x2=function(a){return"string"===typeof a?a:""},y2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},NBa=function(a){this.externalId=a},OBa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},z2=function(a){return a.value?a.value:null},A2=function(a){if(!a)return null;
var b=g.Jc(x2(a.value));b=g.Fc(b);if(!b)return null;var c=y2(a.target,PBa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new OBa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},QBa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},TBa=function(a){if(!a)return null;
var b=y2(a.type,RBa),c=y2(a.trigger,SBa),d=MBa(a.url);d=A2(d?d:null);a=MBa(a.subscribeData);var e=a?a:null;e?(a=x2(e.external_user_id),e=x2(e.subscription_token),a=a&&e?new NBa(a):null):a=null;return b?new QBa(b,c,d,a):null},B2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},UBa=function(a,b){return g.gb(a.action,b,void 0)},VBa=function(a,b){this.context=a;
this.o=b},D2=function(a){return a.customMessage?C2("div","iv-card-message",a.customMessage):""},E2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",O:{style:c},L:d}},F2=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.p(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(C2("li","",c.value));return{D:"ul",I:"iv-card-meta-info",L:b}},C2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Gn(c);return{D:a,O:b,U:c}},WBa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.nq&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.nq+");");c.dir=g.Gn(a.customMessage);var d=[{D:"span",U:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",da:b,O:c,L:d}},G2=function(a,b,c,d){if(d){b=g.p(b);
for(var e=b.next();!e.done;e=b.next())a.o(e.value,d,c.id,c.bd,c.Re.click,5)}},XBa=function(a,b){this.merchant=a;
this.price=b},YBa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ZBa=function(a,b){return b?b:YBa(a)?"current":"new"},H2=function(a,b){g.B.call(this);
var c=this;this.element=a;this.context=b;this.Ca=!1;this.oa=new Map;this.ma=new Map;this.context.G.addEventListener(g.ED("annotations_module"),function(d){(d=c.oa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.FD("annotations_module"),function(d){(d=c.ma.get(d))&&d.apply(c)})},I2=function(a,b,c,d,e,f,h){a.context.o.ia(b,"click",function(){a.xw(c,d,e,f||[],h||0)});
a.context.o.ia(b,"touchstart",function(){a.Ca=!1});
a.context.o.ia(b,"touchmove",function(){a.Ca=!0})},$Ba=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},J2=function(a,b,c){return{nB:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
iF:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
vt:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},M2=function(a,b,c){H2.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.aa=this.bb=this.A=this.jd=!1;this.ca=null;this.cards=[];this.Ha=this.J=this.X=this.C=this.fa=this.o=null;this.P=[];this.H=this.Vc=this.W=null;this.F=0;this.T=new g.G(g.Ma,c.B.Oc?4E3:3E3);g.C(this,this.T);this.wa=new g.G(g.Ma);g.C(this,this.wa);this.S=new VBa(c,function(e,f,h,l,m,n){I2(d,e,f,h,l,m,n)});
this.M=new g.V({D:"div",I:"iv-drawer",O:{id:"iv-drawer"},L:[{D:"div",I:"iv-drawer-header",O:{"aria-role":"heading"},L:[{D:"span",I:"iv-drawer-header-text"},{D:"button",da:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});g.C(this,this.M);this.B=this.M.element;this.ua=new g.FN(this.M,330);g.C(this,this.ua);this.Ja=g.re("iv-drawer-header-text",this.B);this.u=g.re("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.bb&&K2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.bb=d.A)&&L2(d)})},aCa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){K2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){L2(a)});
var d=c.headerText;g.Le(a.Ja,d);a.J&&a.J.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.W=g.Gs(c.trackingParams);a.H=g.Gs(c.closeTrackingParams);a.Vc=g.Gs(c.iconTrackingParams)},bCa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.F;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"simple",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,bd:N2(a,c,b,d),sponsored:!1,Re:J2(d,e,d.command),Yh:d.trackingParams?g.Gs(d.trackingParams):null,gg:e.trackingParams?g.Gs(e.trackingParams):
null,Vc:f&&f.trackingParams?g.Gs(f.trackingParams):null,imageUrl:O2(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.U(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,nq:null,title:d.title?g.U(d.title):"",customMessage:d.callToAction?g.U(d.callToAction):"",url:d.command.urlEndpoint.url?A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};P2(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"collaborator",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,bd:N2(a,c,b,d),sponsored:!1,Re:J2(d,e,d.endpoint),Yh:d.trackingParams?g.Gs(d.trackingParams):null,gg:e.trackingParams?g.Gs(e.trackingParams):null,Vc:f&&f.trackingParams?g.Gs(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.U(d.customText):null,lE:O2(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.U(d.channelName):"",metaInfo:[d.subscriberCountText?g.U(d.subscriberCountText):""],url:A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};P2(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"playlist",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,bd:N2(a,c,b,d),sponsored:!1,Re:J2(d,e,d.action),Yh:d.trackingParams?g.Gs(d.trackingParams):null,gg:e.trackingParams?g.Gs(e.trackingParams):null,Vc:f&&f.trackingParams?g.Gs(f.trackingParams):
null,Dp:O2(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.U(d.customMessage):null,playlistVideoCount:g.U(d.playlistVideoCount),title:d.playlistTitle?g.U(d.playlistTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.videoCountText?g.U(d.videoCountText):""],url:A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:$Ba(d.action)})};P2(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"video",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,bd:N2(a,c,b,d),sponsored:!1,Re:J2(d,e,d.action),Yh:d.trackingParams?g.Gs(d.trackingParams):null,gg:e.trackingParams?g.Gs(e.trackingParams):null,Vc:f&&f.trackingParams?g.Gs(f.trackingParams):null,Dp:O2(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.U(d.lengthString):null,customMessage:d.customMessage?g.U(d.customMessage):null,title:d.videoTitle?g.U(d.videoTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.viewCountText?g.U(d.viewCountText):""],isLiveNow:!!d.badge,url:A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:$Ba(d.action)})};P2(a,c)}a.F++},O2=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},N2=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},dCa=function(a,b){var c=cCa(a,b);
c&&(c===a.o&&(a.o=null),a.G.removeCueRange(c.card.id),g.He(c.Cu),g.qb(a.cards,c),a.qq(),Q2(a))},K2=function(a,b,c){if(!a.A){a.ua.show();
a.fa=new g.G(function(){g.I(a.context.G.getRootNode(),g.$_.IV_DRAWER_OPEN)},0);
a.fa.start();a.ca=g.ap(a.u,"mousewheel",function(h){a.T.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.A=!0;var d=g.Ms();d&&a.W&&a.H&&g.ht(d,[a.W,a.H]);b={TRIGGER_TYPE:b};for(var e=g.p(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.QB||(f.QB=!0,eCa(a.context.logger,f.card.Re.nB,b)),d&&g.ht(d,[f.card.Yh]);c2(a.G);c&&(a.C=new g.G(function(){a.X=a.J;a.Ha.focus()},330),a.C.start())}},L2=function(a){a.A&&(a.ua.hide(),g.bp(a.ca),a.ca=null,g.yn(a.context.G.getRootNode(),g.$_.IV_DRAWER_OPEN),a.A=!1,c2(a.G),a.C&&a.C.stop(),a.C=new g.G(function(){a.X&&(a.X.focus(),a.X=null)},330),a.C.start())},gCa=function(a){g.xn(a.Ea(),
[g.$_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.jP(a.G,a.B,5);fCa(a);a.J=g.re("ytp-cards-button",a.G.getRootNode());a.Ha=g.re("iv-drawer-close-button",a.B);a.jd=!0},fCa=function(a){var b=g.re("iv-drawer-close-button",a.B);
a.context.o.ia(b,"click",a.XG,a);a.context.o.ia(a.u,"touchend",function(){a.T.start()});
a.context.o.ia(a.u,"scroll",a.lH,a);a.context.u.subscribe("onHideControls",function(){a.aa=!0});
a.context.u.subscribe("onShowControls",function(){a.aa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.aa=g.wn(a.G.getRootNode(),"ytp-autohide")});
a.P.push(g.Lo("iv-button-shown",a.LI,a));a.P.push(g.Lo("iv-button-hidden",a.KI,a));a.P.push(g.Lo("iv-teaser-shown",a.IJ,a));a.P.push(g.Lo("iv-teaser-hidden",a.MI,a));a.P.push(g.Lo("iv-teaser-clicked",a.HJ,a))},P2=function(a,b){a.jd||gCa(a);
dCa(a,b.id);var c=hCa(a,b);if(c){var d={card:b,Cu:c.element,QB:!1},e=iCa(a,d);g.wb(a.cards,e,0,d);c.Y(a.u,e);a.qq();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.A||(a.o=d,Q2(a),jCa(a,d),K2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&kCa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){kCa(a,d)}),Q2(a))}},hCa=function(a,b){switch(b.type){case "simple":var c=a.S;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",U:b.displayDomain}:void 0;var e=WBa(b);d={D:"div",da:["iv-card"],L:[{D:"a",I:"iv-click-target",O:{href:b.url?z2(b.url)||"":""},L:[E2(b.imageUrl,d),{D:"div",I:"iv-card-content",L:[C2("h2",void 0,b.title),e]}]}]};d=new g.V(d);G2(c,g.qe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.S,d={D:"div",da:["iv-card","iv-card-channel"],L:[{D:"a",da:["iv-click-target"],O:{href:z2(b.url)||"","data-ytid":b.channelId},L:[E2(b.lE),
{D:"div",I:"iv-card-content",L:[D2(b),{D:"h2",I:"iv-card-primary-link",U:b.title},F2(b)]}]}]},d=new g.V(d),G2(c,g.qe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.S,d={D:"div",da:["iv-card","iv-card-playlist"],L:[{D:"a",I:"iv-click-target",O:{href:z2(b.url)||""},L:[E2(b.Dp,{D:"div",I:"iv-card-image-overlay",L:[{D:"span",I:"iv-card-playlist-video-count",U:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",L:[D2(b),C2("h2","iv-card-primary-link",b.title),F2(b)]}]}]},d=new g.V(d),
G2(c,g.qe("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.S;var f=!g.nb(b.offers);d=["iv-card"];e="";var h=WBa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",I:"iv-card-offer-price",U:h.price}),h.merchant&&f.push({D:"div",I:"iv-card-offer-merchant",U:h.merchant}),h={D:"div",L:f});f=b.url?z2(b.url)||"":"";d={D:"div",da:d,O:{tabindex:"0"},L:[{D:"a",da:["iv-card-image","iv-click-target"],O:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",L:[b.sponsored?{D:"div",I:"iv-card-sponsored",L:["Sponsored",{D:"div",I:"iv-ad-info-container",L:[{D:"div",I:"iv-ad-info",U:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",L:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",O:{href:f},L:[C2("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.De("span");g.Le(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Xb(e,"adInfo");G2(c,g.qe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.S,d=b.isLiveNow?{D:"span",da:["yt-badge","yt-badge-live"],U:"LIVE NOW"}:null,d={D:"div",da:["iv-card","iv-card-video"],L:[{D:"a",I:"iv-click-target",O:{href:z2(b.url)||""},L:[E2(b.Dp,b.videoDuration?{D:"span",I:"iv-card-video-duration",U:b.videoDuration}:void 0),{D:"div",I:"iv-card-content",L:[D2(b),C2("h2","iv-card-primary-link",b.title),F2(b),d]}]}]},d=new g.V(d),G2(c,g.qe("iv-click-target",d.element),
b,b.url),d;default:return null}},iCa=function(a,b){if(0===a.cards.length)return 0;
var c=g.ib(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},lCa=function(a){return a.o?"productListing"===a.o.card.type:g.gh(a.cards,function(b){return"productListing"===b.card.type})},Q2=function(a){g.J(a.G.getRootNode(),"ytp-cards-shopping-active",lCa(a))},kCa=function(a,b){if(!g.wn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.o!==b){var c=g.Ms(),d=a.o?a.o.card.Vc:a.Vc;
c&&d&&g.it(c,[d]);a.o=b;Q2(a)}if(c="none"!=a.Ea().style.display)2===a.context.G.getPresentingPlayerType()?c=1===a.context.G.getAdState():(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.WW(g.NW(a.G)))&&d.qw(!0,c));a.wa.isActive()||((!a.A||!a.T.isActive()&&a.aa)&&jCa(a,b),a.wa.start(910+b.card.teaserDurationMs))}},jCa=function(a,b){if(a.M.Pa){var c=new g2([0,
a.u.scrollTop],[0,b.Cu.offsetTop],600,wBa);a.context.A.ia(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.A.ia(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.MM(a.M,!0),a.u.scrollTop=b.Cu.offsetTop,g.MM(a.M,!1)},R2=function(a){return a.o&&a.o.card?a.o.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},cCa=function(a,b){return g.gb(a.cards,function(c){return c.card.id===b})},S2=function(a,b,c){H2.call(this,a,b);
this.annotation=c;this.isActive=!1},mCa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},T2=function(a,b,c){S2.call(this,a,b,c);
this.u=null;this.H=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},nCa=function(a,b){var c=void 0===c?0:c;
var d=uBa(b).width;g.sg(b,d);c=new i2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,vBa);g.C(a,c);a.context.A.ia(c,"begin",function(){g.Cg(b,!0)});
c.play()},qCa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
da:["iv-branding-context-name"],U:b.channel_name}),d=a.createElement({D:"div",da:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.o=new g.gY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.G),a.o.Y(d));var f=a.createElement({D:"div",da:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",da:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Cg(h,!1);var l=a.createElement({D:"div",da:["branding-context-container-outer"]});l.appendChild(h);g.F(l,"right",b.image_width+"px");a.Ea().appendChild(l);a.A=new g.G(function(){oCa(a,h,l)},500);
g.C(a,a.A);a.context.o.ia(a.Ea(),"mouseover",function(){pCa(a,h,l,f,b.image_height)});
a.context.o.ia(a.Ea(),"mouseout",function(){a.A.start()})}},pCa=function(a,b,c,d,e){a.A.stop();
if(!a.B){var f=g.Bg(b);a.o||(b.style.width=g.rg(f.width,!0),c.style.width=g.rg(f.width,!0));g.F(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.F(d,"right","1px");a.B=!0;g.Cg(b,!0);a.C=new g.G(function(){g.I(this.Ea(),"iv-branding-active")},0,a);
a.C.start()}},oCa=function(a,b,c){g.yn(a.Ea(),"iv-branding-active");
a.F=new g.G(function(){g.Cg(b,!1);a.o||(c.style.width=g.rg(0,!0))},250);
a.F.start();a.B=!1},rCa=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},U2=function(a,b,c){S2.call(this,a,b,c);
var d=this;this.J=this.isCollapsed=this.M=!1;this.F=5E3;this.u=this.A=this.o=this.B=null;this.H=this.createElement({D:"div",da:["iv-promo-contents"]});this.C=new g.G(function(){d.o.setAttribute("aria-hidden","true");g.Cg(d.A,!1);g.Cg(d.u,!0)},700,this);
g.C(this,this.C)},sCa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.F=b.collapsedelay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.Ea().setAttribute("aria-hidden","true");a.Ea().setAttribute("aria-label","Promotion");a.Ea().tabIndex=0;var e=a.annotation.Uc(),f=b.image_url;if(f){var h=a.createElement({D:"div",da:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",O:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({D:"span",I:"iv-promo-video-duration",U:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",I:"iv-promo-playlist-length",U:b.playlist_length.toString()}),h.appendChild(f));e&&I2(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",I:"iv-promo-txt"}),g.gd(f,z2(e)),a.o=f):a.o=a.createElement({D:"div",I:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",L:[{D:"strong",U:b.text_line_1}]});
var m=a.createElement({D:"p",L:[{D:"span",I:"iv-promo-link",U:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",da:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",da:["iv-button","iv-promo-button"],L:[{D:"span",I:"iv-button-content",U:f}]});var q=a.createElement({D:"div",I:"iv-promo-button-container"});q.appendChild(f);e&&I2(a,a.Ea(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");
e&&I2(a,a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",L:[{D:"span",U:b.text_line_1}]}),m=a.createElement({D:"p",L:[{D:"strong",U:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",da:["yt-badge","iv-promo-badge-live"],U:"LIVE NOW"})),g.I(a.o,"iv-click-target"),e&&I2(a,a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);q&&a.H.appendChild(q);c=
a.createElement({D:"div",I:"iv-promo-actions"});a.u=a.createElement({D:"button",da:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.o.ia(a.u,"click",function(r){V2(a,5E3,r)});
c.appendChild(a.u);g.Cg(a.u,!1);a.context.o.ia(a.Ea(),"mouseover",a.eI,a);a.context.o.ia(a.Ea(),"mouseout",a.dI,a);a.context.o.ia(a.Ea(),"touchend",function(r){V2(a,5E3,r)});
a.A=a.createElement({D:"button",da:["iv-promo-close","ytp-button"]});a.A.title="Close";a.context.o.ia(a.A,"click","cta"===a.annotation.style&&b.text_line_3?a.XH:a.WH,a);c.appendChild(a.A);g.xn(a.Ea(),d);h&&(a.Ea().appendChild(h),n&&h.appendChild(n));a.Ea().appendChild(a.H);a.Ea().appendChild(c)},V2=function(a,b,c){c.stopPropagation();
tCa(a);uCa(a,b);a.o.focus()},vCa=function(a){a.isCollapsed||a.J||a.B||(g.I(a.Ea(),"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},tCa=function(a){a.C.stop();
a.isCollapsed&&(g.zn(a.Ea(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Cg(a.u,!1),g.Cg(a.A,!0))},uCa=function(a,b){a.B||(a.B=g.Rm(function(){W2(this);
vCa(this)},b,a))},W2=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},wCa=function(a){this.G=a},eCa=function(a,b,c){b&&(c?X2(a,b.map(function(d){return g.ln(d,c)})):X2(a,b))},X2=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.p(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.rt(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},Y2=function(a){g.AS.call(this,a);
var b=this;this.M=!1;this.loadNumber=0;this.H={};this.logger=new wCa(this.player);this.C=new g.ms(this);this.F=this.A=null;this.events=new g.ms(this);this.J=this.o=null;this.P=[];g.C(this,this.C);this.C.K(this.player,"onVideoAreaChange",function(){b.R("onVideoAreaChange")});
this.C.K(this.player,"onHideControls",function(){b.R("onHideControls")});
this.C.K(this.player,"onShowControls",function(){b.R("onShowControls")});
this.C.K(this.player,"resize",function(d){b.R("resize",d)});
this.C.K(this.player,"presentingplayerstatechange",function(d){b.R("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.GJ,this);this.subscribe("resize",this.Gs,this);this.player.N().M.subscribe("vast_info_card_add",this.UD,this);g.C(this,this.events);this.S=this.createElement({D:"div",I:"video-custom-annotations"});this.u=new g.V({D:"div",da:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.jP(this.player,this.u.element,4);this.u.hide();this.B=new g.V({D:"div",da:["ytp-iv-video-content"]});g.C(this,this.B);a=this.createElement({D:"div",I:"video-annotations"});
a.appendChild(this.S);this.B.element.appendChild(a);xCa(this)&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.$f(this,function(){g.He(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},yCa=function(a){a=a.createElement({D:"div",
da:["annotation","annotation-type-custom"]});g.Cg(a,!1);return a},xCa=function(a){var b=a.player.N();
a=a.player.getVideoData();return 1===(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.MF||b.M.get(a.videoId)||g.SF(a)||g.TF(a)?!0:!1},zCa=function(a,b){var c=!b.isCued()&&!g.T(b,1024);
g.MM(a.u,c);g.MM(a.B,c)},ACa=function(a,b,c){a.M=!0;
a.F=g.mq(b,c)},BCa=function(a,b){for(var c={},d=g.p(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ra(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(BCa(a,e))}return c},ECa=function(a){var b=a.player.getVideoData();
if(b.Mf){var c=a.player.N().M.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.gq(h)&&h.responseXML?h.responseXML:null)&&Z2(a,h)}};
g.qp()&&(d.onFinish=CCa(a,d.onFinish));d.postParams={ic_only:"1"};DCa(d,c);a.M=!0;g.mq(b.Mf,d)}}},DCa=function(a,b){a.method="POST";
a.Lb=a.Lb||{};b.xq&&(a.Lb.ic_coll=b.xq);b.yq&&(a.Lb.ic_xml=b.yq);b.Hp&&(a.Lb.ic_track=b.Hp)},FCa=function(a){var b=new g.V({D:"div"});
g.Cg(b.element,!1);var c=new M2(a.player,b.element,$2(a));g.C(c,b);b.Y(a.u.element);c.qp();return c},$2=function(a){if(!a.J){var b=new j2(a);
g.C(a,b);var c=new g.V0(a);g.C(a,c);a.J=new rCa(b,c,a.player.N(),a.player.getVideoData(),a.logger,a.player,a.bb)}return a.J},Z2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ms();if(e){var f=g.Ks();f&&g.bt(g.ro("use_default_events_client")?void 0:g.zr,e,f,[g.Gs(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=BCa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=y2(h.type,GCa),r=y2(h.style,HCa),t=x2(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=TBa;if(null==x)var z=null;else if(g.Pa(x)){m=[];for(var D=g.p(x),E=D.next();!E.done;E=
D.next()){var H=h(E.value);H&&m.push(H)}z=m}else{var M=h(x);z=M?[M]:[]}f=n&&q?new B2(n,q,r,z,w):null}else f=null}catch(fb){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var P=yCa(h),Qa=null;switch(m.type){case "branding":if(h.player.N().Qa)break;h.u.element.appendChild(P);Qa=new T2(P,$2(h),m);break;case "promotion":g.jP(h.player,P,4),Qa=new U2(P,$2(h),m)}Qa&&Qa.qp();if(h=Qa)g.C(a,h),a.H[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.o||(a.o=FCa(a),g.C(a,a.o));if("card"===f.type){c=
a.o;var kb=f&&f.data&&f.data.card_type;h=f.data;if(kb)switch(m=h.tracking||{},m={nB:m.impression,click:m.click,close:m.close,iF:m.teaser_impression,vt:m.teaser_click},P=h.tracking_params||{},Qa=null,kb){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,bd:h.session_data||{},sponsored:h.sponsored||!1,Re:m,Yh:P.card?g.Gs(P.card):null,gg:P.teaser?g.Gs(P.teaser):null,Vc:P.icon?
g.Gs(P.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,lE:h.image_url,title:h.title,metaInfo:h.meta_info,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};P2(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,bd:h.session_data||{},sponsored:h.sponsored||!1,Re:m,Yh:P.card?g.Gs(P.card):null,
gg:P.teaser?g.Gs(P.teaser):null,Vc:P.icon?g.Gs(P.icon):null,Dp:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};P2(c,f);break;case "productListing":h.signin_url&&(Qa=A2({target:"current",value:h.signin_url}));kb=[];for(var xb=h.offers||[],Wa=0;Wa<xb.length;Wa++)kb.push(new XBa(g.nd(xb[Wa].merchant),g.nd(xb[Wa].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,bd:h.session_data||{},sponsored:h.sponsored||!1,Re:m,Yh:P.card?g.Gs(P.card):null,gg:P.teaser?g.Gs(P.teaser):null,Vc:P.icon?g.Gs(P.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,nq:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),kV:Qa,jV:h.signin_title?h.signin_title:void 0,iV:h.signin_message?h.signin_message:void 0,offers:kb};P2(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,bd:h.session_data||{},sponsored:h.sponsored||!1,Re:m,Yh:P.card?g.Gs(P.card):null,gg:P.teaser?g.Gs(P.teaser):null,Vc:P.icon?
g.Gs(P.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,nq:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};P2(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,bd:h.session_data||{},sponsored:h.sponsored||!1,Re:m,Yh:P.card?g.Gs(P.card):null,gg:P.teaser?g.Gs(P.teaser):null,Vc:P.icon?g.Gs(P.icon):null,Dp:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},P2(c,f)}}else aCa(a.o,f);c=!0}}c&&(c2(a.player),a.Gs())},ICa=function(a,b){var c=!1;
a.o||(a.o=FCa(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(bCa(a.o,e.cardRenderer),c=!0);c&&(c=a.o,d=b.headerText?g.U(b.headerText):"",g.Le(c.Ja,d),c.J&&c.J.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.W=b.trackingParams?g.Gs(b.trackingParams):null,c.H=b.closeButton.infoCardIconRenderer.trackingParams?g.Gs(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Vc=b.icon.infoCardIconRenderer.trackingParams?
g.Gs(b.icon.infoCardIconRenderer.trackingParams):null,c2(a.player),a.Gs())},JCa=function(a,b,c,d,e){if(!a.player.N().Qa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new QBa("openUrl","click",new OBa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.U(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.U(b.subscriberCountText))):(b.subscriberCountText&&(e=g.U(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.U(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.U(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.U(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new B2(c,"branding","branding",f,d);d=yCa(a);a.u.element.appendChild(d);f=new T2(d,$2(a),f);f.qp();g.C(f,f);a.H[c]=f}},CCa=function(a,b){return function(c){for(var d=
[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.ea()||(d.unshift(b),b=g.Ua.apply(window,d),a.P.push(g.op(b)))}},KCa=function(a){return"annotation-editor"===a||"live-dashboard"===a},d2={},e2=null;g.Xa(g2,g.An);g.k=g2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.va)this.progress=0,this.coords=this.o;else if(this.vb())return!1;f2(this);this.startTime=a=g.A();-1==this.va&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Es();this.Pf("play");-1==this.va&&this.Pf("resume");this.va=1;var b=g.Ta(this);b in d2||(d2[b]=this);yBa();zBa(this,a);return!0};
g.k.stop=function(a){f2(this);this.va=0;a&&(this.progress=1);ABa(this,this.progress);this.Pf("stop");this.Qo()};
g.k.pause=function(){this.vb()&&(f2(this),this.va=-1,this.Pf("pause"))};
g.k.V=function(){0==this.va||this.stop(!1);this.Pf("destroy");g2.Pc.V.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.Av=function(){this.Pf("animate")};
g.k.Pf=function(a){this.dispatchEvent(new BBa(a,this))};
g.Xa(BBa,g.Hl);g.Xa(h2,g2);h2.prototype.A=g.Ma;h2.prototype.Av=function(){this.A();h2.Pc.Av.call(this)};
h2.prototype.Qo=function(){this.A();h2.Pc.Qo.call(this)};
h2.prototype.Es=function(){this.A();h2.Pc.Es.call(this)};
g.Xa(i2,h2);i2.prototype.A=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(j2,g.B);j2.prototype.ia=function(a,b,c,d){c=(0,g.y)(c,d||this.u);a=g.ap(a,b,c);this.o.push(a);return a};
j2.prototype.Gr=function(a,b,c,d){c=(0,g.y)(c,d||this.u);a=g.jp(a,b,c);this.o.push(a);return a};
j2.prototype.sb=function(a){g.bp(a);g.qb(this.o,a)};
j2.prototype.V=function(){g.bp(this.o);this.o.length=0;g.B.prototype.V.call(this)};g.u(n2,g.AS);g.k=n2.prototype;g.k.load=function(){g.AS.prototype.load.call(this);if(!o2(this)){var a=g.RF(this.player.getVideoData());a?(a=m2(a,DBa(this)),p2(this,a,!1)):EBa(this)}};
g.k.unload=function(){p2(this,null);this.A&&(this.A.abort(),this.A=null);g.AS.prototype.unload.call(this)};
g.k.Hd=function(a,b){if(!o2(this))return null;if("loadCustomEndscreenRenderer"===a){var c=m2(b,"new");p2(this,c);return!0}return null};
g.k.getOptions=function(){return o2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.La=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<LCa.length;f++){var h=Math.abs(b.width-LCa[f]);if(-1===e||d>=h)e=f,d=h}d=MCa[e];this.u&&g.F(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.o[f],h=
this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.zg(e.element,Math.round(h.width*a.width),f);g.sg(e.element,m,n);g.zn(e.element,NCa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zn(e.element,MCa);g.I(e.element,d);(e=g.pe(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.F(e,"height",f+"px")}}}}};
g.k.mJ=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())w2(this,this.endscreen.impressionUrls),(a=g.Ms())&&this.endscreen.visualElement&&g.ct(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.o[a],c=this.C[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");w2(this,c.impressionUrls);(b=g.Ms())&&g.ct(b,c.visualElement,void 0);this.player.N().A&&this.player.la("endscreenelementshown",
a)}};
g.k.nJ=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.o[a];g.yn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.yn(b,"ytp-ce-shown");this.player.N().A&&this.player.la("endscreenelementhidden",a)}};
g.k.KO=function(a){var b=this;a.target===window&&(new g.G(function(){for(var c=g.p(Object.values(b.o)),d=c.next();!d.done;d=c.next())g.zn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var LCa=[346,426,470,506,570,640,853,1280,1920],MCa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),NCa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var PBa={AR:"current",WS:"new"};var RBa={CLOSE:"close",YS:"openUrl",yG:"subscribe"},SBa={rR:"click",CLOSE:"close",hS:"hidden",IT:"rollOut",JT:"rollOver",QT:"shown"};B2.prototype.Uc=function(){var a=UBa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var HCa={ZQ:"anchored",cG:"branding",CHANNEL:"channel",zR:"cta",kS:"highlightText",zS:"label",PLAYLIST:"playlist",vT:"popup",XT:"speech",yG:"subscribe",kU:"title",VIDEO:"video",yU:"website"},GCa={cG:"branding",jR:"card",FR:"drawer",jS:"highlight",KS:"marker",AT:"promotion",TEXT:"text",AU:"widget"};g.u(H2,g.B);g.k=H2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.BD(a,b,{id:c});a.namespace="annotations_module";d&&this.oa.set(a,d);e&&this.ma.set(a,e);g.uM(this.context.G,[a])};
g.k.qp=function(){this.context.u.subscribe("resize",this.qq,this)};
g.k.Ea=function(){return this.element};
g.k.xw=function(a,b,c,d,e,f){if(this.Ca)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.He(this.Ea())};
g.k.qq=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=z2(a);if(f){var h=ZBa(f,a.target),l=function(){a.o&&e.context.G.pauseVideo();var m=e.context.videoData.Dc||!1,n=g.Vp(f||"");m&&n&&(n.v||n.list)?g.M0(e.context.G.app,n.v,b,n.list,!1,void 0):g.sK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);X2(this.context.logger,c,l,d);YBa(f)||(c=g.Ms(),d=b.itct,c&&d&&g.jt(c,g.Gs(d)))}};
g.k.V=function(){this.oa.clear();this.ma.clear();g.B.prototype.V.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.C(this,a);return a.element};g.u(M2,H2);g.k=M2.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Bg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.qq=function(){var a=this.isAvailable();g.Cg(this.Ea(),a);g.J(this.context.G.getRootNode(),g.$_.IV_DRAWER_ENABLED,a);c2(this.G)};
g.k.destroy=function(){var a=g.WW(g.NW(this.G));a&&a.qw(!1,void 0);try{this.G.getRootNode().removeChild(this.B)}catch(b){}g.Mo(this.P);g.bp(this.ca);this.fa&&this.fa.dispose();this.C&&this.C.dispose();H2.prototype.destroy.call(this)};
g.k.XG=function(){if(this.A){X2(this.context.logger,R2(this).Re.close);var a=g.Ms();a&&this.H&&g.jt(a,this.H);L2(this)}};
g.k.lH=function(){g.J(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.LI=function(){var a=g.Ms(),b=R2(this);b=b?b.Vc:this.Vc;a&&b&&g.ht(a,[b])};
g.k.KI=function(){var a=g.Ms(),b=R2(this);b=b?b.Vc:this.Vc;a&&b&&g.it(a,[b])};
g.k.IJ=function(){var a=R2(this);X2(this.context.logger,a.Re.iF);var b=g.Ms();b&&a&&g.ht(b,[a.gg,a.Vc])};
g.k.MI=function(){var a=g.Ms(),b=R2(this);a&&b&&g.it(a,[b.gg])};
g.k.HJ=function(a){var b=R2(this),c=g.Ms();this.o?a?(a=this.context.logger,X2(a,b.Re.vt),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.gg&&g.jt(c,b.gg)):(a=this.context.logger,X2(a,b.Re.vt),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Vc&&g.jt(c,b.Vc)):(a=this.context.logger,X2(a,b.Re.vt),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Vc&&g.jt(c,this.Vc))};g.u(S2,H2);S2.prototype.qp=function(){H2.prototype.qp.call(this);mCa(this)};
S2.prototype.show=function(){H2.prototype.show.call(this);var a=g.Ms(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.ht(a,[g.Gs(b.itct)])};
S2.prototype.hide=function(){H2.prototype.hide.call(this);var a=g.Ms(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.it(a,[g.Gs(b.itct)])};g.u(T2,S2);
T2.prototype.show=function(){if(!this.isActive){S2.prototype.show.call(this);if(!this.H){g.I(this.Ea(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",da:["branding-img","iv-click-target"],O:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Cg(this.u,!1);var b=this.createElement({D:"div",da:["branding-img-container"]});b.appendChild(this.u);this.Ea().appendChild(b);(b=this.annotation.Uc())&&I2(this,this.u,b,this.annotation.id,a.session_data);
qCa(this,a);this.H=!0}g.Cg(this.Ea(),!0);this.isActive=!0;this.u&&nCa(this,this.u)}};
T2.prototype.hide=function(){this.isActive&&(S2.prototype.hide.call(this),g.Cg(this.Ea(),!1),this.isActive=!1)};
T2.prototype.destroy=function(){this.o&&(this.o.dispose(),this.o=null);S2.prototype.destroy.call(this)};g.u(U2,S2);g.k=U2.prototype;g.k.show=function(){this.isActive||(S2.prototype.show.call(this),this.M||(sCa(this),this.M=!0),g.Cg(this.Ea(),!0),g.Rm(function(){g.yn(this.Ea(),"iv-promo-inactive")},100,this),this.Ea().removeAttribute("aria-hidden"),this.isActive=!0,W2(this),tCa(this),uCa(this,this.F))};
g.k.hide=function(){this.isActive&&(g.I(this.Ea(),"iv-promo-inactive"),this.isActive=!1,this.Ea().setAttribute("aria-hidden","true"))};
g.k.xw=function(a,b,c,d,e,f){return this.isCollapsed?!1:S2.prototype.xw.call(this,a,b,c,d,e,f)};
g.k.eI=function(a){this.J=!0;V2(this,500,a)};
g.k.dI=function(){this.J=!1;vCa(this)};
g.k.WH=function(a){a.stopPropagation();this.hide()};
g.k.XH=function(a){a.stopPropagation();W2(this);this.isCollapsed=!0;g.I(this.Ea(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();S2.prototype.destroy.call(this)};g.u(Y2,g.AS);g.k=Y2.prototype;g.k.Hd=function(a,b){if(!KCa(this.player.N().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.U0(b);c&&Z2(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(dCa(this.o,b),c2(this.player)),!0}return null};
g.k.getOptions=function(){return KCa(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Gs=function(){if(this.B){var a=g.LG(this.player).getVideoContentRect(!0);g.zg(this.B.element,a.width,a.height);g.sg(this.B.element,a.left,a.top)}if(this.o){var b=this.player.li();a=this.o;b=b.width;g.J(a.B,"iv-drawer-small",426>=b);g.J(a.B,"iv-drawer-big",1280<=b)}};
g.k.GJ=function(a){zCa(this,a.state);g.T(a.state,2)&&(this.zo()&&this.aC()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.qw(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.F=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.gq(h)&&h.responseXML?h.responseXML:null)&&(Z2(b,h),g.I(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.AS.prototype.load.call(this);zCa(this,g.sI(this.player));this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.qp()&&(a=CCa(this,a));var e={format:"XML",Ze:a,onError:function(){b.F=null},
kg:{}};c.isPharma&&(e.kg.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.N().M.get(d);f&&DCa(e,f);f=f&&(f.yq||f.xq);if(!c.kq||f)c.Mf?ACa(this,c.Mf,e):(this.A=function(){b.Ia(e)},this.player.addEventListener("videodatachange",this.A));
g.jP(this.player,this.B.element,4);this.Gs();(f=g.SF(c))&&ICa(this,f);(f=g.TF(c))&&f.featuredChannel&&JCa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Ia=function(a){var b=this.player.getVideoData();b.Mf&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),ACa(this,b.Mf,a))};
g.k.unload=function(){g.cX(this.player,"annotations_module");for(var a=g.p(Object.keys(this.H)),b=a.next();!b.done;b=a.next())this.H[b.value].destroy();this.J=null;this.o&&(this.o.destroy(),this.o=null,c2(this.player));this.M=!1;this.F&&(this.F.abort(),this.F=null);this.H={};this.u.hide();g.AS.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.UD=function(a){a===this.player.getVideoData().videoId&&(this.loaded?ECa(this):this.load())};
g.k.zo=function(){return!!this.o&&this.o.isAvailable()};
g.k.aC=function(){this.zo();return!!this.o&&this.o.A};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.zo();this.o&&(a?c?K2(this.o,c,b):K2(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):L2(this.o))};
g.k.qw=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.V=function(){this.player.N().M.unsubscribe("vast_info_card_add",this.UD,this);g.yn(this.player.getRootNode(),g.$_.IV_DRAWER_OPEN);for(var a=this.P,b=0,c=a.length;b<c;b++)g.rp(a[b]);this.P.length=0;g.AS.prototype.V.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.C(this,a);return a.element};g.qX.annotations_module=Y2;g.qX.creatorendscreen=n2;})(_yt_player);
